[package]
name = "huniq"
version = "2.1.0"
authors = ["Karolin Varner <karo@cupdev.net>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Filter out duplicates on the command line. Replacement for `sort | uniq` optimized for speed (10x faster)."
readme = "readme.md"
repository = "https://github.com/koraa/huniq"
categories = ["command-line-utilities"]
keywords = ["cli", "uniq"]

[dependencies]
clap = "^2.33.0"
anyhow = "^1.0.26"
sysconf = "^0.3.4"
getrandom = "^0.1.14"
memchr = "2.3.3"

[build-dependencies]
bindgen = "^0.52.0"
cc = { version = "^1.0.48", features = ["parallel"] }
anyhow = "^1.0.26"
shell-words = "^0.1.0"
